<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ab76ddd8-b489-4351-9747-9b58af1c9305</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Salon.Domen\Salon.Domen.csproj" />
    <ProjectReference Include="..\Salon.Infrastruktura\Salon.Infrastruktura.csproj" />
    <ProjectReference Include="..\Zajednicko.Poruke\Zajednicko.Poruke.csproj" />
  </ItemGroup>

</Project>
