// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salon.Infrastruktura.Podaci;

#nullable disable

namespace Salon.Infrastruktura.Podaci.Migracije
{
    [DbContext(typeof(SalonKontekst))]
    [Migration("20260812173814_DodajStatusObradeRezervacije")]
    partial class DodajStatusObradeRezervacije
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Salon.Domen.Entiteti.DozvoljenaValuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DozvoljeneValute");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.KategorijaUsluge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KategorijeUsluga");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.OsnovneInformacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDoKadaVaziPopust")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RadnoVreme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OsnovneInformacije");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.PromoKod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumKoriscenja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("RezervacijaId")
                        .IsUnique();

                    b.ToTable("PromoKodovi");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumOtkazivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IzabranaValuta")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("KonacnaCena")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Kurs")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Popust")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("UkupnaCena")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.StavkaRezervacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetka")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.HasIndex("UslugaId");

                    b.ToTable("StavkeRezervacija");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.Usluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("KategorijaUslugeId")
                        .HasColumnType("int");

                    b.Property<int>("MaksimalanBrojKlijenataPoTerminu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrajanjeUMinutima")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetkaPrvogTermina")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("VremeZavrsetkaPoslednjegTermina")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaUslugeId");

                    b.ToTable("Usluge");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.ZahtevZaRezervaciju", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIzmene")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdZahteva")
                        .HasColumnType("char(36)");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdZahteva")
                        .IsUnique();

                    b.HasIndex("RezervacijaId");

                    b.ToTable("ZahteviZaRezervaciju");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.PromoKod", b =>
                {
                    b.HasOne("Salon.Domen.Entiteti.Rezervacija", "Rezervacija")
                        .WithOne()
                        .HasForeignKey("Salon.Domen.Entiteti.PromoKod", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.StavkaRezervacije", b =>
                {
                    b.HasOne("Salon.Domen.Entiteti.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salon.Domen.Entiteti.Usluga", "Usluga")
                        .WithMany()
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.Usluga", b =>
                {
                    b.HasOne("Salon.Domen.Entiteti.KategorijaUsluge", "KategorijaUsluge")
                        .WithMany("Usluge")
                        .HasForeignKey("KategorijaUslugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijaUsluge");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.ZahtevZaRezervaciju", b =>
                {
                    b.HasOne("Salon.Domen.Entiteti.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.KategorijaUsluge", b =>
                {
                    b.Navigation("Usluge");
                });
#pragma warning restore 612, 618
        }
    }
}
