// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salon.Infrastruktura.Podaci;

#nullable disable

namespace Salon.Infrastruktura.Podaci.Migracije
{
    [DbContext(typeof(SalonKontekst))]
    partial class SalonKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Salon.Domen.Entiteti.DozvoljenaValuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DozvoljeneValute");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.KategorijaUsluge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KategorijeUsluga");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.OsnovneInformacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDoKadaVaziPopust")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RadnoVreme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OsnovneInformacije");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.Usluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("KategorijaUslugeId")
                        .HasColumnType("int");

                    b.Property<int>("MaksimalanBrojKlijenataPoTerminu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrajanjeUMinutima")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetkaPrvogTermina")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("VremeZavrsetkaPoslednjegTermina")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaUslugeId");

                    b.ToTable("Usluge");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.Usluga", b =>
                {
                    b.HasOne("Salon.Domen.Entiteti.KategorijaUsluge", "KategorijaUsluge")
                        .WithMany("Usluge")
                        .HasForeignKey("KategorijaUslugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategorijaUsluge");
                });

            modelBuilder.Entity("Salon.Domen.Entiteti.KategorijaUsluge", b =>
                {
                    b.Navigation("Usluge");
                });
#pragma warning restore 612, 618
        }
    }
}
