// <auto-generated />
using System;
using Izvestavanje.Api.Podaci;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Izvestavanje.Api.Migrations
{
    [DbContext(typeof(IzvestavanjeKontekst))]
    [Migration("20260818005641_PocetnaIzvestavanjeBaza")]
    partial class PocetnaIzvestavanjeBaza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Izvestavanje.Api.Entiteti.IzvestajnaRezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RezervacijaIdA1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaIdA1")
                        .IsUnique();

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Izvestavanje.Api.Entiteti.IzvestajnaStavkaRezervacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IzvestajnaRezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaUslugeId")
                        .HasColumnType("int");

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremePocetka")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("IzvestajnaRezervacijaId");

                    b.HasIndex("KategorijaUslugeId");

                    b.ToTable("StavkeRezervacija");
                });

            modelBuilder.Entity("Izvestavanje.Api.Entiteti.ObradjenDogadjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipDogadjaja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("VremeObrade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId")
                        .IsUnique();

                    b.ToTable("ObradjeniDogadjaji");
                });

            modelBuilder.Entity("Izvestavanje.Api.Entiteti.IzvestajnaStavkaRezervacije", b =>
                {
                    b.HasOne("Izvestavanje.Api.Entiteti.IzvestajnaRezervacija", "IzvestajnaRezervacija")
                        .WithMany("Stavke")
                        .HasForeignKey("IzvestajnaRezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzvestajnaRezervacija");
                });

            modelBuilder.Entity("Izvestavanje.Api.Entiteti.IzvestajnaRezervacija", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
